### ISSUE TITLE
Issues while using it with Material AngularJS

### ISSUE THREAD

**Issue by sasivarnan** [zavoloklom/material-design-iconic-font#28] opened 2015-03-13 11:07 UTC
I am trying to use this material design iconic font in a project with Material Angular JS. Both Material Angular and material design iconic font elements having classes starting with "md-". But due to the way that this CSS is implemented, styles in this [class*=" md-"],[class^=md-] gets applied to Material Angular components too.

Kindly fix it to be compatible with that too.

Suggested fix: 
Change your existing CSS to i[class*=" md-"], i[class^=md-] instead of  [class*=" md-"],[class^=md-], as the icons are embedded using <i> tag.

Thanks in advance.

**Comment by mjaverto** [comment] 2015-03-15 22:48
Isn't this a duplicate of https://github.com/zavoloklom/material-design-iconic-font/issues/10?

**Comment by sasivarnan** [comment] 2015-03-20 07:12
Hi @mjaverto.
Yup I haven't noticed that issue #10. 
So I made a fork of it with the solution that I have suggested. You can find that here.
https://github.com/sasivarnan/material-design-iconic-font

**Comment by Jossef** [comment] 2015-04-08 14:15
###  You can customize this prefix

by using less / sass, you have the ability to change the default `md` prefix to anything you want

1. **Copy** from the bower install location the content of `.../scss/material-design-iconic-font.scss` to a local project file
2. **Add** after importing `_variables.scss` a new line that overrides `$md-css-prefix`

-----

**_md-icons.scss** *(change from `md` to `mdi`)*

```scss

@import "../../lib/material-design-iconic-font/scss/variables";

$md-css-prefix: mdi;

@import "../../lib/material-design-iconic-font/scss/mixins";
@import "../../lib/material-design-iconic-font/scss/path";
@import "../../lib/material-design-iconic-font/scss/core";
@import "../../lib/material-design-iconic-font/scss/sizes";
@import "../../lib/material-design-iconic-font/scss/border";
@import "../../lib/material-design-iconic-font/scss/pulled";
@import "../../lib/material-design-iconic-font/scss/spinned";
@import "../../lib/material-design-iconic-font/scss/rotated";
@import "../../lib/material-design-iconic-font/scss/icons";

```

and this is the result:

![image](https://cloud.githubusercontent.com/assets/1287098/7047002/5cbce7dc-de12-11e4-8d31-78bcfc10c13a.png)

**Closed** 2015-06-18 07:24 UTC
